[project]
name = "davep-github-com"
version = "0.1.0"
description = "Build system for blog.davep.org"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pelican[markdown]>=4.11.0.post0",
]
